# coding: utf-8
from collections import namedtuple
SubwayStation = namedtuple('SubwayStation', ['id', 'name'])
SubwayLine = namedtuple('SubwayLine', ['id', 'name', 'stations'])


all_subway_lines = [
    SubwayLine('1', u'Сокольническая', [
        SubwayStation(1, u'Бульвар Рокоссовского'),
        SubwayStation(2, u'Черкизовская'),
        SubwayStation(3, u'Преображенская площадь'),
        SubwayStation(4, u'Сокольники'),
        SubwayStation(5, u'Красносельская'),
        SubwayStation(6, u'Комсомольская'),
        SubwayStation(7, u'Красные ворота'),
        SubwayStation(8, u'Чистые пруды'),
        SubwayStation(9, u'Лубянка'),
        SubwayStation(10, u'Охотный ряд'),
        SubwayStation(11, u'Библиотека имени Ленина'),
        SubwayStation(12, u'Кропоткинская'),
        SubwayStation(13, u'Парк культуры'),
        SubwayStation(14, u'Фрунзенская'),
        SubwayStation(15, u'Спортивная'),
        SubwayStation(16, u'Воробьёвы горы'),
        SubwayStation(17, u'Университет'),
        SubwayStation(18, u'Проспект Вернадского'),
        SubwayStation(19, u'Юго-Западная'),
        SubwayStation(20, u'Тропарёво'),
        SubwayStation(21, u'Румянцево'),
        SubwayStation(22, u'Саларьево'),
    ]),
    SubwayLine('2', u'Замоскворецкая', [
        SubwayStation(23, u'Речной вокзал'),
        SubwayStation(24, u'Водный стадион'),
        SubwayStation(25, u'Войковская'),
        SubwayStation(26, u'Сокол'),
        SubwayStation(27, u'Аэропорт'),
        SubwayStation(28, u'Динамо'),
        SubwayStation(29, u'Белорусская'),
        SubwayStation(30, u'Маяковская'),
        SubwayStation(31, u'Тверская'),
        SubwayStation(32, u'Театральная'),
        SubwayStation(33, u'Новокузнецкая'),
        SubwayStation(34, u'Павелецкая'),
        SubwayStation(35, u'Автозаводская'),
        SubwayStation(36, u'Технопарк'),
        SubwayStation(37, u'Коломенская'),
        SubwayStation(38, u'Каширская'),
        SubwayStation(39, u'Кантемировская'),
        SubwayStation(40, u'Царицыно'),
        SubwayStation(41, u'Орехово'),
        SubwayStation(42, u'Домодедовская'),
        SubwayStation(43, u'Красногвардейская'),
        SubwayStation(44, u'Алма-Атинская'),
    ]),
    SubwayLine('3', u'Арбатско-Покровская', [
        SubwayStation(45, u'Пятницкое шоссе'),
        SubwayStation(46, u'Митино'),
        SubwayStation(47, u'Волоколамская'),
        SubwayStation(48, u'Мякинино'),
        SubwayStation(49, u'Строгино'),
        SubwayStation(50, u'Крылатское'),
        SubwayStation(51, u'Молодёжная'),
        SubwayStation(52, u'Кунцевская'),
        SubwayStation(53, u'Славянский бульвар'),
        SubwayStation(54, u'Парк Победы'),
        SubwayStation(55, u'Киевская'),
        SubwayStation(56, u'Смоленская'),
        SubwayStation(57, u'Арбатская'),
        SubwayStation(58, u'Площадь Революции'),
        SubwayStation(59, u'Курская'),
        SubwayStation(60, u'Бауманская'),
        SubwayStation(61, u'Электрозаводская'),
        SubwayStation(62, u'Семёновская'),
        SubwayStation(63, u'Партизанская'),
        SubwayStation(64, u'Измайловская'),
        SubwayStation(65, u'Первомайская'),
        SubwayStation(66, u'Щёлковская'),
    ]),
    SubwayLine('4', u'Филёвская', [
        SubwayStation(67, u'Кунцевская'),
        SubwayStation(68, u'Пионерская'),
        SubwayStation(69, u'Филёвский парк'),
        SubwayStation(70, u'Багратионовская'),
        SubwayStation(71, u'Фили'),
        SubwayStation(72, u'Кутузовская'),
        SubwayStation(73, u'Студенческая'),
        SubwayStation(74, u'Международная'),
        SubwayStation(75, u'Выставочная'),
        SubwayStation(76, u'Киевская'),
        SubwayStation(77, u'Смоленская'),
        SubwayStation(78, u'Арбатская'),
        SubwayStation(79, u'Александровский сад'),
    ]),
    SubwayLine('5', u'Кольцевая', [
        SubwayStation(80, u'Парк культуры'),
        SubwayStation(81, u'Октябрьская'),
        SubwayStation(82, u'Добрынинская'),
        SubwayStation(83, u'Павелецкая'),
        SubwayStation(84, u'Таганская'),
        SubwayStation(85, u'Курская'),
        SubwayStation(86, u'Комсомольская'),
        SubwayStation(87, u'Проспект Мира'),
        SubwayStation(88, u'Новослободская'),
        SubwayStation(89, u'Белорусская'),
        SubwayStation(90, u'Краснопресненская'),
        SubwayStation(91, u'Киевская'),
    ]),
    SubwayLine('6', u'Калужско-Рижская', [
        SubwayStation(92, u'Медведково'),
        SubwayStation(93, u'Бабушкинская'),
        SubwayStation(94, u'Свиблово'),
        SubwayStation(95, u'Ботанический сад'),
        SubwayStation(96, u'ВДНХ'),
        SubwayStation(97, u'Алексеевская'),
        SubwayStation(98, u'Рижская'),
        SubwayStation(99, u'Проспект Мира'),
        SubwayStation(100, u'Сухаревская'),
        SubwayStation(101, u'Тургеневская'),
        SubwayStation(102, u'Китай-город'),
        SubwayStation(103, u'Третьяковская'),
        SubwayStation(104, u'Октябрьская'),
        SubwayStation(105, u'Шаболовская'),
        SubwayStation(106, u'Ленинский проспект'),
        SubwayStation(107, u'Академическая'),
        SubwayStation(108, u'Профсоюзная'),
        SubwayStation(109, u'Новые Черёмушки'),
        SubwayStation(110, u'Калужская'),
        SubwayStation(111, u'Беляево'),
        SubwayStation(112, u'Коньково'),
        SubwayStation(113, u'Тёплый Стан'),
        SubwayStation(114, u'Ясенево'),
        SubwayStation(115, u'Новоясеневская'),
    ]),
    SubwayLine('7', u'Таганско-Краснопресненская', [
        SubwayStation(116, u'Планерная'),
        SubwayStation(117, u'Сходненская'),
        SubwayStation(118, u'Тушинская'),
        SubwayStation(119, u'Спартак'),
        SubwayStation(120, u'Щукинская'),
        SubwayStation(121, u'Октябрьское поле'),
        SubwayStation(122, u'Полежаевская'),
        SubwayStation(123, u'Беговая'),
        SubwayStation(124, u'Улица 1905 года'),
        SubwayStation(125, u'Баррикадная'),
        SubwayStation(126, u'Пушкинская'),
        SubwayStation(127, u'Кузнецкий мост'),
        SubwayStation(128, u'Китай-город'),
        SubwayStation(129, u'Таганская'),
        SubwayStation(130, u'Пролетарская'),
        SubwayStation(131, u'Волгоградский проспект'),
        SubwayStation(132, u'Текстильщики'),
        SubwayStation(133, u'Кузьминки'),
        SubwayStation(134, u'Рязанский проспект'),
        SubwayStation(135, u'Выхино'),
        SubwayStation(136, u'Лермонтовский проспект'),
        SubwayStation(137, u'Жулебино'),
        SubwayStation(138, u'Котельники'),
    ]),
    SubwayLine('8a', u'Солнцевский радиус Калининско-Солнцевской', [
        SubwayStation(139, u'Раменки'),
        SubwayStation(140, u'Ломоносовский проспект'),
        SubwayStation(141, u'Минская'),
        SubwayStation(142, u'Парк Победы'),
        SubwayStation(143, u'Деловой центр'),
    ]),
    SubwayLine('8', u'Калининский радиус Калининско-Солнцевской', [
        SubwayStation(144, u'Третьяковская'),
        SubwayStation(145, u'Марксистская'),
        SubwayStation(146, u'Площадь Ильича'),
        SubwayStation(147, u'Авиамоторная'),
        SubwayStation(148, u'Шоссе Энтузиастов'),
        SubwayStation(149, u'Перово'),
        SubwayStation(150, u'Новогиреево'),
        SubwayStation(151, u'Новокосино'),
    ]),
    SubwayLine('9', u'Серпуховско-Тимирязевская', [
        SubwayStation(152, u'Алтуфьево'),
        SubwayStation(153, u'Бибирево'),
        SubwayStation(154, u'Отрадное'),
        SubwayStation(155, u'Владыкино'),
        SubwayStation(156, u'Петровско-Разумовская'),
        SubwayStation(157, u'Тимирязевская'),
        SubwayStation(158, u'Дмитровская'),
        SubwayStation(159, u'Савёловская'),
        SubwayStation(160, u'Менделеевская'),
        SubwayStation(161, u'Цветной бульвар'),
        SubwayStation(162, u'Чеховская'),
        SubwayStation(163, u'Боровицкая'),
        SubwayStation(164, u'Полянка'),
        SubwayStation(165, u'Серпуховская'),
        SubwayStation(166, u'Тульская'),
        SubwayStation(167, u'Нагатинская'),
        SubwayStation(168, u'Нагорная'),
        SubwayStation(169, u'Нахимовский проспект'),
        SubwayStation(170, u'Севастопольская'),
        SubwayStation(171, u'Чертановская'),
        SubwayStation(172, u'Южная'),
        SubwayStation(173, u'Пражская'),
        SubwayStation(174, u'Улица академика Янгеля'),
        SubwayStation(175, u'Аннино'),
        SubwayStation(176, u'Бульвар Дмитрия Донского'),
    ]),
    SubwayLine('10', u'Люблинско-Дмитровская', [
        SubwayStation(177, u'Петровско-Разумовская'),
        SubwayStation(178, u'Фонвизинская'),
        SubwayStation(179, u'Бутырская'),
        SubwayStation(180, u'Марьина роща'),
        SubwayStation(181, u'Достоевская'),
        SubwayStation(182, u'Трубная'),
        SubwayStation(183, u'Сретенский бульвар'),
        SubwayStation(184, u'Чкаловская'),
        SubwayStation(185, u'Римская'),
        SubwayStation(186, u'Крестьянская застава'),
        SubwayStation(187, u'Дубровка'),
        SubwayStation(188, u'Кожуховская'),
        SubwayStation(189, u'Печатники'),
        SubwayStation(190, u'Волжская'),
        SubwayStation(191, u'Люблино'),
        SubwayStation(192, u'Братиславская'),
        SubwayStation(193, u'Марьино'),
        SubwayStation(194, u'Борисово'),
        SubwayStation(195, u'Шипиловская'),
        SubwayStation(196, u'Зябликово'),
    ]),
    SubwayLine('11a', u'Каховская', [
        SubwayStation(197, u'Каширская'),
        SubwayStation(198, u'Варшавская'),
        SubwayStation(199, u'Каховская'),
    ]),
    SubwayLine('12', u'Бутовская', [
        SubwayStation(200, u'Битцевский парк'),
        SubwayStation(201, u'Лесопарковая'),
        SubwayStation(202, u'Улица Старокачаловская'),
        SubwayStation(203, u'Улица Скобелевская'),
        SubwayStation(204, u'Бульвар адмирала Ушакова'),
        SubwayStation(205, u'Улица Горчакова'),
        SubwayStation(206, u'Бунинская аллея'),
    ]),
    SubwayLine('13', u'Монорельс', [
        SubwayStation(207, u'Тимирязевская'),
        SubwayStation(208, u'Улица Милашенкова'),
        SubwayStation(209, u'Телецентр'),
        SubwayStation(210, u'Улица Академика Королёва'),
        SubwayStation(211, u'Выставочный центр'),
        SubwayStation(212, u'Улица Сергея Эйзенштейна'),
    ]),
    SubwayLine('14', u'МЦК', [
        SubwayStation(213, u'Окружная'),
        SubwayStation(214, u'Владыкино'),
        SubwayStation(215, u'Ботанический сад'),
        SubwayStation(216, u'Ростокино'),
        SubwayStation(217, u'Белокаменная'),
        SubwayStation(218, u'Бульвар Рокоссовского'),
        SubwayStation(219, u'Локомотив'),
        SubwayStation(220, u'Измайлово'),
        SubwayStation(221, u'Соколиная Гора'),
        SubwayStation(222, u'Шоссе Энтузиастов'),
        SubwayStation(223, u'Андроновка'),
        SubwayStation(224, u'Нижегородская'),
        SubwayStation(225, u'Новохохловская'),
        SubwayStation(226, u'Угрешская'),
        SubwayStation(227, u'Дубровка'),
        SubwayStation(228, u'Автозаводская'),
        SubwayStation(229, u'ЗИЛ'),
        SubwayStation(230, u'Верхние Котлы'),
        SubwayStation(231, u'Крымская'),
        SubwayStation(232, u'Площадь Гагарина'),
        SubwayStation(233, u'Лужники'),
        SubwayStation(234, u'Кутузовская'),
        SubwayStation(235, u'Деловой центр'),
        SubwayStation(236, u'Шелепиха'),
        SubwayStation(237, u'Хорошёво'),
        SubwayStation(238, u'Зорге'),
        SubwayStation(239, u'Панфиловская'),
        SubwayStation(240, u'Стрешнево'),
        SubwayStation(241, u'Балтийская'),
        SubwayStation(242, u'Коптево'),
        SubwayStation(243, u'Лихоборы'),
    ]),
]

all_conjunctions = [
    [1, 218],
    [2, 219],
    [6, 86],
    [8, 101, 183],
    [9, 127],
    [10, 32, 58],
    [11, 57, 79, 163],
    [13, 80],
    [15, 233],

    [25, 241],
    [29, 89],
    [31, 126, 162],
    [33, 103, 144],
    [34, 83],
    [35, 228],
    [38, 197],
    [43, 196],

    [52, 67],
    [54, 142],
    [55, 76, 91],
    [59, 85, 184],
    [63, 220],

    [72, 234],
    [74, 235],
    [75, 143],

    [81, 104],
    [82, 165],
    [84, 129, 145],
    [87, 99],
    [88, 160],
    [90, 125],

    [95, 215],
    [96, 211],
    [102, 128],
    [106, 232],
    [115, 200],

    [121, 239],
    [122, 237],
    [130, 186],
    [146, 185],
    [148, 222],

    [155, 214],
    [156, 177],
    [157, 207],
    [161, 182],
    [170, 199],
    [176, 202],

    [178, 208],
    [187, 227],
]

